name: benchmark
description: A sample command-line application.

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  benchmark_harness: ^1.0.5
  crypto: ^2.0.6
  libsodium:
    path: '../'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
